create table tb_clientes (
    data_nascimento date, 
    id integer generated by default as identity, 
    cpf varchar(14) not null unique, 
    nome varchar(100) not null, 
    endereco varchar(255), 
    primary key (id)
);

create table tb_contatos (
    cliente_id integer not null, 
    id integer generated by default as identity, 
    tipo varchar(50) not null, 
    valor varchar(100) not null, 
    observacao varchar(255), 
    primary key (id)
);

alter table if exists tb_contatos 
add constraint FKiu8qqskx8422s7p98iw5mciga 
foreign key (cliente_id) references tb_clientes on delete cascade;